version: '3.2'

services:
  traefik:
    image: traefik:v2.4
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik
      - ./traefik/certs/fullchain.pem:/cert.pem
      - ./traefik/certs/privkey.pem:/key.pem
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"
      placement:
        constraints:
          - "node.role == manager"
    environment:
      - TRAEFIK_PROVIDERS_DOCKER_DEFAULTRULE="Host(`\{\{ trimPrefix `/` .Name \}\}.${domain}`)"
    command:
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--accesslog.filepath=/dev/stdout"

        #  minio:
        #    image: minio/minio
        #    env_file: ./minio.env
        #    ports:
        #      - 9000:9000
        #    volumes:
        #      - ./volumes/minio:/data
        #    networks:
        #      - traefik-net
        #    command: minio server /data --console-address ":9001"
        #    deploy:
        #      labels:
        #        - "traefik.enable=true"
        #        - "traefik.docker.network=wt_traefik-net"
        #        - "traefik.http.routers.minio.rule=Host(`minio.${domain}`)"
        #        - "traefik.http.routers.minio.entrypoints=websecure"
        #        - "traefik.http.routers.minio.tls=true"
        #        - "traefik.http.routers.minio.service=minio"
        #        - "traefik.http.services.minio.loadbalancer.server.port=9000"
        #        - "traefik.http.services.minio.loadbalancer.passhostheader=true"
        #        - "traefik.http.routers.minio-console.rule=Host(`minio-console.${domain}`)"
        #        - "traefik.http.routers.minio-console.entrypoints=websecure"
        #        - "traefik.http.routers.minio-console.tls=true"
        #        - "traefik.http.routers.minio-console.service=minio-console"
        #        - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
        #        - "traefik.http.services.minio-console.loadbalancer.passhostheader=true"

  mongo:
    image: mongo:4.4
    networks:
      - mongo
    volumes:
      - mongo-data:/data/db
      - mongo-cfg:/data/configdb
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"

  girder:
    image: xarthisius/girder:5-dev
    networks:
      - traefik-net
      - celery
      - mongo
    volumes:
      - ./volumes:/srv/data
      - ./workspace.yaml:/girder/workspace.yaml
      - ./src/girder-wholetale:/girder-plugins/02-girder-wholetale
      - ./src/girder-virtual-resources:/girder-plugins/01-girder-virtual-resources
     # - ./src/minio_assetstore:/girder/plugins/minio_assetstore
     # - ./src/synced_folders:/girder/plugins/synced_folders
     # - ./src/sem_viewer:/girder/plugins/sem_viewer
     # - ./src/table_view:/girder/plugins/table_view
     # - ./src/item_previews:/girder/plugins/item_previews
     # - ./src/dataflows:/girder/plugins/dataflows
     # - ./src/sample_tracker:/girder/plugins/sample_tracker
      - ./src/gwvolman:/gwvolman
      - ./src/girderfs:/girderfs
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    environment:
      - DOMAIN=${domain}
      - DASHBOARD_URL=https://dashboard.${domain}
      - GIRDER_MONGO_URI=mongodb://mongo:27017/girder
      - GIRDER_HOST=0.0.0.0
      - GOSU_USER=1001:1001:${docker_group}
      - GOSU_CHOWN=/srv/data
      - DATAONE_URL=https://cn-stage-2.test.dataone.org/cn
      - GIRDER_LOCAL_FONTELLO_ARCHIVE=/girder/clients/web/static/built/fontello.zip
      - HOSTDIR=/
    extra_hosts:
      - "images.${domain}:host-gateway"
      - "minio.${domain}:host-gateway"
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.girder.rule=Host(`girder.${domain}`)"
        - "traefik.http.routers.girder.entrypoints=websecure"
        - "traefik.http.routers.girder.tls=true"
        - "traefik.http.routers.girder.tls.certresolver=default"
        - "traefik.http.routers.girder.tls.domains[0].main=${domain}"
        - "traefik.http.routers.girder.tls.domains[0].sans=*.${domain}"
        - "traefik.http.services.girder.loadbalancer.server.port=8080"
        - "traefik.http.services.girder.loadbalancer.passhostheader=true"
        - "traefik.docker.network=wt_traefik-net"
        - "traefik.http.middlewares.girder.forwardauth.address=http://girder:8080/api/v1/user/authorize/"
        - "traefik.http.middlewares.girder.forwardauth.trustforwardheader=true"

  logger:
    image: xarthisius/wt-instance-logger:latest
    networks:
      - celery
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"

  redis:
    image: redis:7-bullseye
    networks:
      - celery
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"

  dashboard:
    image: xarthisius/wt-dashboard:latest
    networks:
      - traefik-net
    environment:
      - GIRDER_API_URL=https://girder.${domain}/api/v1
      - AUTH_PROVIDER=Globus
      - DATAONE_URL=https://cn.dataone.org/cn/v2
      - RTD_URL=https://wholetale.readthedocs.io/en/latest
      - DASHBOARD_DEV=true
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dashboard.rule=Host(`dashboard.${domain}`)"
        - "traefik.http.routers.dashboard.entrypoints=websecure"
        - "traefik.http.routers.dashboard.tls=true"
        - "traefik.http.services.dashboard.loadbalancer.server.port=80"
        - "traefik.http.services.dashboard.loadbalancer.passhostheader=true"
        - "traefik.docker.network=wt_traefik-net"
    volumes:
      - ./src/ngx-dashboard/dist/browser/:/usr/share/nginx/html/

  instance-errors:
    image: xarthisius/wt-custom-errors:latest
    networks:
      - traefik-net
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.instance-errors.rule=HostRegexp(`{host:tmp-.*}`)"
        - "traefik.http.routers.instance-errors.entrypoints=websecure"
        - "traefik.http.routers.instance-errors.tls=true"
        - "traefik.http.routers.instance-errors.priority=1"
        - "traefik.http.routers.instance-errors.middlewares=error-pages-middleware"
        - "traefik.http.middlewares.error-pages-middleware.errors.status=400-599"
        - "traefik.http.middlewares.error-pages-middleware.errors.service=instance-errors"
        - "traefik.http.middlewares.error-pages-middleware.errors.query=/{status}.html"
        - "traefik.http.services.instance-errors.loadbalancer.server.port=80"
        - "traefik.docker.network=wt_traefik-net"

  registry:
    image: registry:2.8
    networks:
      - traefik-net
    volumes:
      - ./registry:/var/lib/registry
      - ./registry/auth:/auth:ro
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm"
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/registry.password
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.registry.rule=Host(`registry.${domain}`)"
        - "traefik.http.routers.registry.entrypoints=websecure"
        - "traefik.http.routers.registry.tls=true"
        - "traefik.http.services.registry.loadbalancer.server.port=5000"
        - "traefik.http.services.registry.loadbalancer.passhostheader=true"
        - "traefik.docker.network=wt_traefik-net"

  images:
    image: registry:2.8
    networks:
      - traefik-net
    volumes:
      - ./registry:/var/lib/registry:ro
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.images.rule=Host(`images.${domain}`)"
        - "traefik.http.routers.images.rule=Method(`GET`)"
        - "traefik.http.routers.images.entrypoints=websecure"
        - "traefik.http.routers.images.tls=true"
        - "traefik.http.services.images.loadbalancer.server.port=5000"
        - "traefik.http.services.images.loadbalancer.passhostheader=true"
        - "traefik.docker.network=wt_traefik-net"

  celery_worker:
    image: xarthisius/gwvolman:latest
    networks:
      - celery
    labels:
      - "traefik.enable=false"
    environment:
      - GOSU_USER=ubuntu:1000:${docker_group}
      - DOMAIN=${domain}
      - DEV=true
      - REPO2DOCKER_VERSION=${r2d_version}
      - GIRDERFS_IMAGE=${girderfs_image}
      - TRAEFIK_NETWORK=wt_traefik-net
      - TRAEFIK_ENTRYPOINT=websecure
      - REGISTRY_USER=${registry_user}
      - REGISTRY_URL=https://registry.${domain}
      - REGISTRY_PASS=${registry_pass}
      - WT_LICENSE_PATH=${PWD}/volumes/licenses
      - WT_VOLUMES_PATH=${PWD}/volumes
      - MATLAB_FILE_INSTALLATION_KEY=${matlab_file_installation_key}
      - SWARM_NODE_ID={{.Node.ID}}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/tmp:/tmp
      - ./src/gwvolman:/gwvolman
      - ./src/girderfs:/girderfs
      - type: bind
        source: ${PWD}/volumes
        target: ${PWD}/volumes
        bind:
          propagation: rshared
    extra_hosts:
      - "registry.${domain}:host-gateway"
      - "images.${domain}:host-gateway"
      - "girder.${domain}:host-gateway"
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
    command: -c 3

  postgresql:
    image: postgres:11
    networks:
      - dagster
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres_db

  dagster_web:
    image: xarthisius/dagster:latest
    depends_on:
      - postgresql
    entrypoint: ["dagster-webserver", "-h", "0.0.0.0", "-p", "3000", "-w", "workspace.yaml"]
    networks:
      - traefik-net
      - dagster
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dagster.rule=Host(`dagster.${domain}`)"
        - "traefik.http.routers.dagster.entrypoints=websecure"
        - "traefik.http.routers.dagster.tls=true"
        - "traefik.http.services.dagster.loadbalancer.server.port=3000"
        - "traefik.http.services.dagster.loadbalancer.passhostheader=true"
        - "traefik.docker.network=wt_traefik-net"
    environment:
      - DAGSTER_POSTGRES_USER=postgres_user
      - DAGSTER_POSTGRES_PASSWORD=postgres_password
      - DAGSTER_POSTGRES_DB=postgres_db
    extra_hosts:
      - "girder.${domain}:host-gateway"
    volumes:
      - ./workspace.yaml:/opt/dagster/dagster_home/workspace.yaml
      - ./dagster.yaml:/opt/dagster/dagster_home/dagster.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/io_manager_storage:/tmp/io_manager_storage

  dagster_daemon:
    image: xarthisius/dagster:latest
    entrypoint: ["dagster-daemon", "run"]
    environment:
      - DAGSTER_POSTGRES_USER=postgres_user
      - DAGSTER_POSTGRES_PASSWORD=postgres_password
      - DAGSTER_POSTGRES_DB=postgres_db
    volumes:
      - ./workspace.yaml:/opt/dagster/dagster_home/workspace.yaml
      - ./dagster.yaml:/opt/dagster/dagster_home/dagster.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/io_manager_storage:/tmp/io_manager_storage
    extra_hosts:
      - "girder.${domain}:host-gateway"
    networks:
      - dagster
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"


networks:
  traefik-net:
    driver: overlay
  mongo:
    driver: overlay
  celery:
    driver: overlay
    attachable: true
  dagster:
    driver: overlay
    attachable: true

volumes:
  mongo-data: {}
  mongo-cfg: {}
